# Generated by Django 4.2.5 on 2023-09-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_date_alter_event_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='admin',
            new_name='host',
        ),
    ]
